

create table pagos (
                       id bigint generated by default as identity,
                       amount double,
                       date timestamp,
                       debt double,
                       loan_id bigint,
                       primary key (id)
);

create table prestamos (
                           id bigint generated by default as identity,
                           user_id bigint,
                           amount double,
                           date timestamp,
                           rate double,
                           target varchar(255),
                           term integer,
                           primary key (id)
);

create table usuarios (
                          id bigint generated by default as identity,
                          cantidad_prestamos integer,
                          fecha_creacion timestamp,
                          identificacion varchar(255),
                          nombre varchar(255),
                          volumen_prestamos integer,
                          primary key (id)
);
insert into usuarios (id, nombre, identificacion,cantidad_prestamos, volumen_prestamos,fecha_creacion) values
    (default, 'daniel', '1144076347', 1, 30000, current_date );
insert into usuarios (id, nombre, identificacion,cantidad_prestamos, volumen_prestamos,fecha_creacion) values
    (default, 'Angee', '159487', 4, 700000, current_date );
insert into usuarios (id, nombre, identificacion,cantidad_prestamos, volumen_prestamos,fecha_creacion) values
    (default, 'Jose', '84753456', 6, 1200000, current_date );
insert into usuarios (id, nombre, identificacion,cantidad_prestamos, volumen_prestamos,fecha_creacion) values
    (default, 'Ana', '78912354', 3, 60000, current_date );
insert into usuarios (id, nombre, identificacion,cantidad_prestamos, volumen_prestamos,fecha_creacion) values
    (default, 'Jimmy', '7914628', 9, 4000000, current_date );